#!/bin/bash
#
# OCServ France Server Setup Script
# اسکریپت نصب و تنظیم سرور فرانسه (سرور خارجی)
#
# Usage: bash <(curl -sL https://raw.githubusercontent.com/Ghost-falcon00/ocserv-panel/main/france-setup.sh)
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Print banner
print_banner() {
    echo -e "${PURPLE}"
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║                                                           ║"
    echo "║     OCServ France Server Setup                            ║"
    echo "║     اسکریپت نصب سرور فرانسه (خارجی)                       ║"
    echo "║                                                           ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# Print status messages
info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[✓]${NC} $1"; }
warning() { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[✗]${NC} $1"; exit 1; }

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root (sudo)"
    fi
}

# Detect OS
detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$ID
        VERSION=$VERSION_ID
    else
        error "Cannot detect OS"
    fi
    
    if [[ "$OS" != "ubuntu" && "$OS" != "debian" ]]; then
        error "This script only supports Ubuntu/Debian"
    fi
    
    info "Detected: $OS $VERSION"
}

# Install dependencies
install_dependencies() {
    info "Installing dependencies..."
    apt-get update -qq
    apt-get install -y -qq ocserv gnutls-bin curl wget > /dev/null 2>&1
    success "Dependencies installed"
}

# Get server IP
get_server_ip() {
    SERVER_IP=$(curl -s4 ifconfig.me || curl -s4 icanhazip.com || echo "")
    if [ -z "$SERVER_IP" ]; then
        error "Cannot detect server IP"
    fi
    info "Server IP: $SERVER_IP"
}

# Create SSL certificate
create_ssl() {
    info "Creating self-signed SSL certificate..."
    
    mkdir -p /etc/ocserv/ssl
    
    # Generate CA
    certtool --generate-privkey --outfile /etc/ocserv/ssl/ca-key.pem 2>/dev/null
    
    cat > /tmp/ca.tmpl << EOF
cn = "OCServ CA"
organization = "OCServ"
serial = 1
expiration_days = 3650
ca
signing_key
cert_signing_key
crl_signing_key
EOF
    
    certtool --generate-self-signed \
        --load-privkey /etc/ocserv/ssl/ca-key.pem \
        --template /tmp/ca.tmpl \
        --outfile /etc/ocserv/ssl/ca-cert.pem 2>/dev/null
    
    # Generate server cert
    certtool --generate-privkey --outfile /etc/ocserv/ssl/server-key.pem 2>/dev/null
    
    cat > /tmp/server.tmpl << EOF
cn = "$SERVER_IP"
organization = "OCServ"
serial = 2
expiration_days = 3650
signing_key
encryption_key
tls_www_server
EOF
    
    certtool --generate-certificate \
        --load-privkey /etc/ocserv/ssl/server-key.pem \
        --load-ca-certificate /etc/ocserv/ssl/ca-cert.pem \
        --load-ca-privkey /etc/ocserv/ssl/ca-key.pem \
        --template /tmp/server.tmpl \
        --outfile /etc/ocserv/ssl/server-cert.pem 2>/dev/null
    
    rm -f /tmp/ca.tmpl /tmp/server.tmpl
    
    success "SSL certificate created"
}

# Create OCServ configuration
create_config() {
    info "Creating OCServ configuration..."
    
    # Get port from user
    echo ""
    echo -e "${CYAN}پورت OCServ را انتخاب کنید:${NC}"
    echo "1) 2083 (پیشنهادی - کمتر فیلتر میشه)"
    echo "2) 443 (استاندارد HTTPS)"
    echo "3) Custom (خودم انتخاب میکنم)"
    echo ""
    read -p "انتخاب [1-3]: " port_choice
    
    case $port_choice in
        1) OCSERV_PORT=2083 ;;
        2) OCSERV_PORT=443 ;;
        3) read -p "پورت دلخواه: " OCSERV_PORT ;;
        *) OCSERV_PORT=2083 ;;
    esac
    
    cat > /etc/ocserv/ocserv.conf << EOF
# OCServ Configuration - Optimized for Iran Tunnel
# Generated by france-setup.sh

# Authentication
auth = "plain[passwd=/etc/ocserv/ocpasswd]"

# Ports
tcp-port = $OCSERV_PORT
udp-port = 0

# Performance & Security
run-as-user = nobody
run-as-group = daemon
socket-file = /run/ocserv.socket
isolate-workers = false

# SSL Certificate
server-cert = /etc/ocserv/ssl/server-cert.pem
server-key = /etc/ocserv/ssl/server-key.pem

# Connection Limits
max-clients = 128
max-same-clients = 4

# Timeouts optimized for Iran
keepalive = 32400
dpd = 90
mobile-dpd = 1800
switch-to-tcp-timeout = 25

# MTU optimization
try-mtu-discovery = false
mtu = 1280

# TLS optimization (Anti-DPI)
tls-priorities = "NORMAL:%SERVER_PRECEDENCE:%COMPAT:-VERS-SSL3.0"

# Timeouts
auth-timeout = 240
idle-timeout = 1200
mobile-idle-timeout = 2400
min-reauth-time = 300
rekey-time = 172800
rekey-method = ssl

# Security
max-ban-score = 80
ban-reset-time = 1200
cookie-timeout = 300
deny-roaming = false

# System
use-occtl = true
pid-file = /run/ocserv.pid

# Network
device = vpns
predictable-ips = true
ipv4-network = 192.168.100.0
ipv4-netmask = 255.255.255.0

# DNS
dns = 1.1.1.1
dns = 8.8.8.8

# Routing
tunnel-all-dns = true

# Cisco compatibility
cisco-client-compat = true
dtls-legacy = true

# Disable compression (anti-DPI)
compression = false
EOF

    success "OCServ configured on port $OCSERV_PORT"
}

# Create default user
create_user() {
    info "Creating VPN user..."
    
    echo ""
    read -p "نام کاربری VPN: " VPN_USER
    read -s -p "رمز عبور VPN: " VPN_PASS
    echo ""
    
    echo "$VPN_PASS" | ocpasswd -c /etc/ocserv/ocpasswd "$VPN_USER"
    
    success "User '$VPN_USER' created"
}

# Enable IP forwarding
enable_forwarding() {
    info "Enabling IP forwarding..."
    
    echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-ocserv.conf
    sysctl -p /etc/sysctl.d/99-ocserv.conf > /dev/null 2>&1
    
    success "IP forwarding enabled"
}

# Configure firewall
configure_firewall() {
    info "Configuring firewall..."
    
    # Get default interface
    DEFAULT_IF=$(ip route | grep default | awk '{print $5}' | head -1)
    
    # Allow OCServ port
    iptables -I INPUT -p tcp --dport $OCSERV_PORT -j ACCEPT
    
    # NAT for VPN clients  
    iptables -t nat -A POSTROUTING -s 192.168.100.0/24 -o $DEFAULT_IF -j MASQUERADE
    iptables -A FORWARD -s 192.168.100.0/24 -j ACCEPT
    iptables -A FORWARD -d 192.168.100.0/24 -j ACCEPT
    
    # MSS clamping
    iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1240
    
    # Save rules
    if command -v netfilter-persistent &> /dev/null; then
        netfilter-persistent save > /dev/null 2>&1
    else
        apt-get install -y -qq iptables-persistent > /dev/null 2>&1
        netfilter-persistent save > /dev/null 2>&1
    fi
    
    success "Firewall configured"
}

# Start OCServ
start_ocserv() {
    info "Starting OCServ..."
    
    systemctl enable ocserv > /dev/null 2>&1
    systemctl restart ocserv
    
    sleep 2
    
    if systemctl is-active --quiet ocserv; then
        success "OCServ is running"
    else
        error "Failed to start OCServ"
    fi
}

# Print summary
print_summary() {
    echo ""
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║              نصب با موفقیت انجام شد! ✓                    ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${CYAN}اطلاعات سرور:${NC}"
    echo -e "  IP سرور:      ${YELLOW}$SERVER_IP${NC}"
    echo -e "  پورت OCServ:  ${YELLOW}$OCSERV_PORT${NC}"
    echo -e "  کاربر VPN:    ${YELLOW}$VPN_USER${NC}"
    echo ""
    echo -e "${CYAN}مرحله بعدی:${NC}"
    echo -e "  1. روی سرور ایران، پنل OCServ رو نصب کن"
    echo -e "  2. وارد بخش 'تانل' شو"
    echo -e "  3. IP این سرور ($SERVER_IP) و پورت ($OCSERV_PORT) رو وارد کن"
    echo -e "  4. تانل رو روشن کن"
    echo ""
    echo -e "${PURPLE}═══════════════════════════════════════════════════════════${NC}"
}

# Main installation
main() {
    print_banner
    check_root
    detect_os
    get_server_ip
    install_dependencies
    create_ssl
    create_config
    create_user
    enable_forwarding
    configure_firewall
    start_ocserv
    print_summary
}

# Run main
main
