#!/bin/bash
#
# OCServ France Server Setup Script
# اسکریپت نصب و تنظیم سرور فرانسه (سرور خارجی)
# شامل Remote API برای سینک با پنل ایران
#
# Usage: bash <(curl -sL https://raw.githubusercontent.com/Ghost-falcon00/ocserv-panel/main/france-setup.sh)
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Print banner
print_banner() {
    echo -e "${PURPLE}"
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║                                                           ║"
    echo "║     OCServ France Server Setup                            ║"
    echo "║     اسکریپت نصب سرور فرانسه (خارجی)                       ║"
    echo "║     + Remote API for Panel Sync                           ║"
    echo "║                                                           ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# Print status messages
info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[✓]${NC} $1"; }
warning() { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[✗]${NC} $1"; exit 1; }

# Generate random string
generate_token() {
    python3 -c "import secrets; print(secrets.token_urlsafe(48))" 2>/dev/null || \
    openssl rand -base64 48 | tr -d '/+=' | head -c 48
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root (sudo)"
    fi
}

# Detect OS
detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$ID
        VERSION=$VERSION_ID
    else
        error "Cannot detect OS"
    fi
    
    if [[ "$OS" != "ubuntu" && "$OS" != "debian" ]]; then
        error "This script only supports Ubuntu/Debian"
    fi
    
    info "Detected: $OS $VERSION"
}

# Install dependencies
install_dependencies() {
    info "Installing dependencies..."
    apt-get update -qq
    apt-get install -y -qq ocserv gnutls-bin curl wget python3 python3-pip python3-venv unzip > /dev/null 2>&1
    success "Dependencies installed"
}

# Get server IP
get_server_ip() {
    SERVER_IP=$(curl -s4 ifconfig.me || curl -s4 icanhazip.com || echo "")
    if [ -z "$SERVER_IP" ]; then
        error "Cannot detect server IP"
    fi
    info "Server IP: $SERVER_IP"
}

# Create SSL certificate
create_ssl() {
    info "Creating self-signed SSL certificate..."
    
    mkdir -p /etc/ocserv/ssl
    
    # Generate CA
    certtool --generate-privkey --outfile /etc/ocserv/ssl/ca-key.pem 2>/dev/null
    
    cat > /tmp/ca.tmpl << EOF
cn = "OCServ CA"
organization = "OCServ"
serial = 1
expiration_days = 3650
ca
signing_key
cert_signing_key
crl_signing_key
EOF
    
    certtool --generate-self-signed \
        --load-privkey /etc/ocserv/ssl/ca-key.pem \
        --template /tmp/ca.tmpl \
        --outfile /etc/ocserv/ssl/ca-cert.pem 2>/dev/null
    
    # Generate server cert
    certtool --generate-privkey --outfile /etc/ocserv/ssl/server-key.pem 2>/dev/null
    
    cat > /tmp/server.tmpl << EOF
cn = "$SERVER_IP"
organization = "OCServ"
serial = 2
expiration_days = 3650
signing_key
encryption_key
tls_www_server
EOF
    
    certtool --generate-certificate \
        --load-privkey /etc/ocserv/ssl/server-key.pem \
        --load-ca-certificate /etc/ocserv/ssl/ca-cert.pem \
        --load-ca-privkey /etc/ocserv/ssl/ca-key.pem \
        --template /tmp/server.tmpl \
        --outfile /etc/ocserv/ssl/server-cert.pem 2>/dev/null
    
    rm -f /tmp/ca.tmpl /tmp/server.tmpl
    
    success "SSL certificate created"
}

# Create OCServ configuration
create_config() {
    info "Creating OCServ configuration..."
    
    # Get port from user
    echo ""
    echo -e "${CYAN}پورت OCServ را انتخاب کنید:${NC}"
    echo "1) 2083 (پیشنهادی - کمتر فیلتر میشه)"
    echo "2) 443 (استاندارد HTTPS)"
    echo "3) Custom (خودم انتخاب میکنم)"
    echo ""
    read -p "انتخاب [1-3]: " port_choice
    
    case $port_choice in
        1) OCSERV_PORT=2083 ;;
        2) OCSERV_PORT=443 ;;
        3) read -p "پورت دلخواه: " OCSERV_PORT ;;
        *) OCSERV_PORT=2083 ;;
    esac
    
    cat > /etc/ocserv/ocserv.conf << EOF
# OCServ Configuration - Full Stealth Mode
# Generated by france-setup.sh
# تمام امضاهای سیسکو حذف شدن - ترافیک شبیه وبسایت عادی‌ه

# Authentication
auth = "plain[passwd=/etc/ocserv/ocpasswd]"

# Ports - DTLS غیرفعال (مهم‌ترین علامت شناسایی سیسکو)
tcp-port = $OCSERV_PORT
udp-port = 0

# Performance & Security
run-as-user = nobody
run-as-group = daemon
socket-file = /run/ocserv.socket
isolate-workers = false

# SSL Certificate
server-cert = /etc/ocserv/ssl/server-cert.pem
server-key = /etc/ocserv/ssl/server-key.pem

# Connection Limits
max-clients = 128
max-same-clients = 4

# Timeouts optimized for Iran
keepalive = 32400
dpd = 90
mobile-dpd = 1800
switch-to-tcp-timeout = 25

# MTU optimization
try-mtu-discovery = false
mtu = 1280

# TLS fingerprint مثل مرورگر عادی (نه سیسکو)
tls-priorities = "NORMAL:%SERVER_PRECEDENCE:%COMPAT:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1:+VERS-TLS1.3:-RSA:-DHE-RSA:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC"

# Timeouts
auth-timeout = 240
idle-timeout = 1200
mobile-idle-timeout = 2400
min-reauth-time = 300

# Rekey سریع - شناسایی سخت‌تر
rekey-time = 172800
rekey-method = ssl

# Security
max-ban-score = 80
ban-reset-time = 1200
cookie-timeout = 300
deny-roaming = false

# System
use-occtl = true
pid-file = /run/ocserv.pid

# Network
device = vpns
predictable-ips = true
ipv4-network = 192.168.100.0
ipv4-netmask = 255.255.255.0

# DNS
dns = 1.1.1.1
dns = 8.8.8.8

# Routing
tunnel-all-dns = true

# سازگاری Cisco بدون امضای واضح
cisco-client-compat = true
dtls-legacy = false

# =============================================
# Anti-Detection & Cisco Signature Removal
# =============================================
# هدرهای جعلی nginx/PHP - فایروال فکر میکنه یه سایت عادیه
custom-header = "Server: nginx/1.24.0"
custom-header = "X-Powered-By: PHP/8.2.12"
custom-header = "X-Content-Type-Options: nosniff"
custom-header = "X-Frame-Options: SAMEORIGIN"
custom-header = "X-XSS-Protection: 1; mode=block"
custom-header = "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload"
custom-header = "Content-Security-Policy: default-src 'self' https: data: 'unsafe-inline'"
custom-header = "Referrer-Policy: strict-origin-when-cross-origin"
custom-header = "Permissions-Policy: camera=(), microphone=(), geolocation=()"
custom-header = "Cache-Control: no-cache, no-store, must-revalidate"
custom-header = "Pragma: no-cache"
custom-header = "Vary: Accept-Encoding"
custom-header = "X-DNS-Prefetch-Control: off"

# فشرده‌سازی غیرفعال (anti-DPI)
compression = false

# Stats reset
server-stats-reset-time = 0
EOF
    
    success "OCServ configured on port $OCSERV_PORT (Full Stealth Mode)"
}

# Create default user
create_user() {
    info "Creating VPN user..."
    
    echo ""
    read -p "نام کاربری VPN: " VPN_USER
    read -s -p "رمز عبور VPN: " VPN_PASS
    echo ""
    
    echo "$VPN_PASS" | ocpasswd -c /etc/ocserv/ocpasswd "$VPN_USER"
    
    success "User '$VPN_USER' created"
}

# Enable IP forwarding
enable_forwarding() {
    info "Enabling IP forwarding..."
    
    echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-ocserv.conf
    sysctl -p /etc/sysctl.d/99-ocserv.conf > /dev/null 2>&1
    
    success "IP forwarding enabled"
}

# Configure firewall
configure_firewall() {
    info "Configuring firewall..."
    
    # Get default interface
    DEFAULT_IF=$(ip route | grep default | awk '{print $5}' | head -1)
    
    # Allow OCServ port
    iptables -I INPUT -p tcp --dport $OCSERV_PORT -j ACCEPT
    
    # Allow Remote API port
    iptables -I INPUT -p tcp --dport $API_PORT -j ACCEPT
    
    # NAT for VPN clients  
    iptables -t nat -A POSTROUTING -s 192.168.100.0/24 -o $DEFAULT_IF -j MASQUERADE
    iptables -A FORWARD -s 192.168.100.0/24 -j ACCEPT
    iptables -A FORWARD -d 192.168.100.0/24 -j ACCEPT
    
    # MSS clamping
    iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1240
    
    # Save rules - NONINTERACTIVE (بدون سوال - جلوی هنگ رو میگیره)
    if ! command -v netfilter-persistent &> /dev/null; then
        echo iptables-persistent iptables-persistent/autosave_v4 boolean true | debconf-set-selections
        echo iptables-persistent iptables-persistent/autosave_v6 boolean true | debconf-set-selections
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq iptables-persistent > /dev/null 2>&1
    fi
    netfilter-persistent save > /dev/null 2>&1 || true
    
    success "Firewall configured"
}

# Install Remote API for panel sync
install_remote_api() {
    info "Installing Remote API for panel sync..."
    
    # Generate API token
    API_TOKEN=$(generate_token)
    
    # Get API port
    API_PORT=${API_PORT:-6443}
    
    # Create directories
    mkdir -p /opt/ocserv-remote
    mkdir -p /etc/ocserv-remote
    
    # Save token
    echo "$API_TOKEN" > /etc/ocserv-remote/token
    chmod 600 /etc/ocserv-remote/token
    
    # Download remote API files
    GITHUB_RAW="https://raw.githubusercontent.com/Ghost-falcon00/ocserv-panel/main"
    MIRROR_RAWS=(
        "$GITHUB_RAW"
        "https://gh-proxy.com/$GITHUB_RAW"
        "https://ghproxy.net/$GITHUB_RAW"
    )
    
    DOWNLOADED=false
    for raw_url in "${MIRROR_RAWS[@]}"; do
        if timeout 10 curl -sL "$raw_url/remote-api/remote_api.py" -o /opt/ocserv-remote/remote_api.py 2>/dev/null; then
            if [[ -s /opt/ocserv-remote/remote_api.py ]]; then
                timeout 10 curl -sL "$raw_url/remote-api/requirements.txt" -o /opt/ocserv-remote/requirements.txt 2>/dev/null
                DOWNLOADED=true
                break
            fi
        fi
    done
    
    if [[ "$DOWNLOADED" == "false" ]]; then
        warning "Could not download remote API files, creating inline..."
        # Create minimal inline version
        cat > /opt/ocserv-remote/requirements.txt << 'REQEOF'
fastapi==0.104.1
uvicorn==0.24.0
pydantic==2.5.0
REQEOF
    fi
    
    # Create Python venv and install deps
    cd /opt/ocserv-remote
    python3 -m venv venv
    source venv/bin/activate
    pip install -q --upgrade pip
    pip install -q -r requirements.txt 2>&1 | tail -3
    deactivate
    
    # Create systemd service
    cat > /etc/systemd/system/ocserv-remote-api.service << EOF
[Unit]
Description=OCServ Remote API
After=network.target ocserv.service

[Service]
Type=simple
User=root
WorkingDirectory=/opt/ocserv-remote
Environment=REMOTE_API_PORT=$API_PORT
Environment=REMOTE_API_TOKEN=$API_TOKEN
ExecStart=/opt/ocserv-remote/venv/bin/python /opt/ocserv-remote/remote_api.py
Restart=always
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF
    
    systemctl daemon-reload
    systemctl enable ocserv-remote-api > /dev/null 2>&1
    systemctl start ocserv-remote-api
    
    sleep 2
    
    if systemctl is-active --quiet ocserv-remote-api; then
        success "Remote API installed and running on port $API_PORT"
    else
        warning "Remote API installed but may need manual start"
    fi
}

# Start OCServ
start_ocserv() {
    info "Starting OCServ..."
    
    systemctl enable ocserv > /dev/null 2>&1
    systemctl restart ocserv
    
    sleep 2
    
    if systemctl is-active --quiet ocserv; then
        success "OCServ is running"
    else
        error "Failed to start OCServ"
    fi
}

# Print summary
print_summary() {
    echo ""
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║              نصب با موفقیت انجام شد! ✓                    ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${CYAN}═══ اطلاعات سرور ═══${NC}"
    echo -e "  IP سرور:        ${YELLOW}$SERVER_IP${NC}"
    echo -e "  پورت OCServ:    ${YELLOW}$OCSERV_PORT${NC}"
    echo -e "  کاربر VPN:      ${YELLOW}$VPN_USER${NC}"
    echo ""
    echo -e "${CYAN}═══ اطلاعات Remote API (برای سینک پنل) ═══${NC}"
    echo -e "  پورت API:       ${YELLOW}$API_PORT${NC}"
    echo -e "  توکن API:       ${YELLOW}$API_TOKEN${NC}"
    echo ""
    echo -e "${RED}⚠️  توکن API رو یادداشت کن! بدون این، پنل ایران نمیتونه سینک بشه${NC}"
    echo ""
    echo -e "${CYAN}═══ مرحله بعدی ═══${NC}"
    echo -e "  1. وارد پنل ایران شو"
    echo -e "  2. برو به بخش ${YELLOW}'تانل'${NC}"
    echo -e "  3. اطلاعات زیر رو وارد کن:"
    echo -e "     - IP سرور فرانسه: ${YELLOW}$SERVER_IP${NC}"
    echo -e "     - پورت OCServ:    ${YELLOW}$OCSERV_PORT${NC}"
    echo -e "     - پورت API:       ${YELLOW}$API_PORT${NC}"
    echo -e "     - توکن API:       ${YELLOW}$API_TOKEN${NC}"
    echo -e "  4. 'ذخیره و اتصال' رو بزن"
    echo ""
    echo -e "${PURPLE}═══════════════════════════════════════════════════════════${NC}"
    
    # Save info to file
    cat > /root/ocserv-info.txt << EOF
OCServ France Server Info
=========================
Server IP:      $SERVER_IP
OCServ Port:    $OCSERV_PORT
VPN User:       $VPN_USER
API Port:       $API_PORT
API Token:      $API_TOKEN
=========================
EOF
    echo -e "${CYAN}اطلاعات در فایل /root/ocserv-info.txt ذخیره شد${NC}"
}

# Main installation
main() {
    print_banner
    check_root
    detect_os
    get_server_ip
    install_dependencies
    create_ssl
    create_config
    create_user
    enable_forwarding
    API_PORT=6443
    install_remote_api
    configure_firewall
    start_ocserv
    print_summary
}

# Run main
main
